# Generated by Django 4.1 on 2022-08-31 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('get_item_bool', models.BooleanField(default=False)),
                ('required_item_bool', models.BooleanField(default=False)),
                ('new_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='find_item_choices', to='remyapi.item')),
                ('outcome_situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_choices', to='remyapi.situation')),
                ('required_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_item_choices', to='remyapi.item')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resulting_choices', to='remyapi.situation')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remyapi.character')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remyapi.choice')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='current_situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='remyapi.situation'),
        ),
        migrations.AddField(
            model_name='character',
            name='items',
            field=models.ManyToManyField(related_name='characters', to='remyapi.item'),
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
    ]
