# Generated by Django 4.1 on 2022-09-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remyapi', '0003_alter_characterchoice_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
