# Generated by Django 4.1 on 2022-09-06 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remyapi', '0004_choice_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterchoice',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_choices', to='remyapi.choice'),
        ),
    ]
